### ISSUE TITLE
Sometimes cuts off the end of the input value

### ISSUE THREAD

**Issue by JKGisMe** [tim-evans/ember-autoresize#24]
Not sure what is causing this but we've tried to fix it a couple of times and it keeps recurring. We are using ember-autoresize for the title input in https://github.com/ember-cli/ember-twiddle. It seems to sporadically cut off the last character in the input. Not always and not reproducible (at least not that we've found). I've attached a screen shot where you can see half of the last `e` in `New Twiddle` gets cut off. 

Wondered if you guys had seen anything like this before or knew what could be going on here?

<img width="1259" alt="twiddle-signin-old" src="https://cloud.githubusercontent.com/assets/3296888/9778195/f696baf6-5732-11e5-8b6c-cb7450c379f2.png">

Some of the times we've tried to address it:
https://github.com/ember-cli/ember-twiddle/issues/187
https://github.com/ember-cli/ember-twiddle/pull/190#discussion-diff-38857033
https://github.com/ember-cli/ember-twiddle/commit/c9d57d6882d7fe02b73a08715273c51268d37ef1

**Comment by tim-evans** [comment]
Yeah, I've seen this. I think this has to do with how the measurement is done in https://github.com/tim-evans/dom-ruler. 

I think that changing https://github.com/tim-evans/ember-autoresize/blob/master/addon/mixins/autoresize.js#L165 to schedule a new measurement when the element is inserted into the DOM might help.

**Comment by tim-evans** [comment]
I also have a hunch that the measurement is affected by the font being loaded after the measurement occurs. I'll dig into approaches that try to see whether a font has been loaded.

**Comment by tim-evans** [comment]
It consistently is off-by-2, where if you dig into the ember-inspector and grab the text field, the `measuredSize` property has a width of `87px`, but if you run the measurement by hand:

```javascript
measureText = require('dom-ruler')['default'].measureText;
measureText(text, {}, { template: $E.get('element'), escape: false });
```

It has a width of `89px`. A lot of work here is shooting in the dark trying to find out *why* the browser changed the size of the element between subsequent measures that are effectively stateless. The most consistent aspect of this seems to be fonts. If we can find a way to detect when a font has been loaded and emit events for the autoresized field to remeasure, then I believe that will solve this problem.

**Comment by JKGisMe** [comment]
Thanks for looking into this! It was really stumping us and I was about to resort to adding a space to the end of everything. I'll look at it more when I get home tonight.

**Comment by JKGisMe** [comment]
Hm, so I was looking into this last night and everything I can find about how to tell when fonts load relate to just listening for the size of text to change. Which is all we need to listen for to run `scheduleMeasurement()` anyway, right?

I tried to run the `scheduleMeasurement()` on `didRender`, `afterRender`, `didInsertElement` but nothing worked. I can only get it to adjust correctly through the console.

**Comment by tim-evans** [comment]
:< Looks like this is gonna have to pull in a font loading detector library. Or roll it ourselves.

**Comment by JKGisMe** [comment]
I looked at one, and it literally was just measuring some hidden dummy text every some number of ms until it changed.

**Comment by tim-evans** [comment]
Yeah, we can work that into the addon, then I think. The other neat way of doing it was using a custom adobe font that has zero width characters as a fallback.

**Comment by tim-evans** [comment]
Lemme know if ember-twiddle works better with 0.5.5.

**Comment by tim-evans** [comment]
Sorry, make that 0.5.6. There was a bad upstream bower version of dom-ruler.
