### ISSUE TITLE
HierarchyRequestError in iOs 8.3 Safari 

### ISSUE THREAD

**Issue by mattmcmanus** [tim-evans/ember-autoresize#25]
`HierarchyRequestError: DOM Exception 3: A Node was inserted somewhere it doesn't belong.`

It's taken me about 6 hours to finally pin this down. I can walk you through the details if you're interested but I'll assume you want to be spared. 

The gist: I get the above error when:

1. Using an old iphone, (I can replicated it using the simulator with iOS 8.3 and safari AND
2. Transitioning to a page that has an autoresizing textarea (not directly loading the page) AND
3. The site's built using the production env (doesn't happen in dev)

I've tracked it down to your `injectAdobeBlank()` function in `system/font-loaded.js`. If I comment out the contents of that function I do not receive the error and everything *works*

I feel a little crazy because of how ridiculously specific this is. I'm not sure it's of any use. How necessary is adobe blank?

```
Ember                     : 1.13.10
Ember Data                : 1.13.11
ember-autoresize                 : 0.5.10
```

**Comment by tim-evans** [comment]
It's of use if you're using custom fonts. It seems like the stylesheet injection may be the problem

**Comment by tim-evans** [comment]
Want to try `0.5.11` for ember-autoresize? It's a shot in the dark @_@

**Comment by mattmcmanus** [comment]
Thanks for the quick response! Trying 0.5.11 now

Seems like textareas with custom fonts are a much smaller use case. What about a attribute?

```
{{textarea autoresize=true custom-font=true}}
```

It would default to false and then load all the other extra stuff only when you really need it?

**Comment by tim-evans** [comment]
It's textareas or inputs with custom fonts. There's an issue where you may not know whether it's available on the user's system. There may be a series of fallbacks that can only be determined by the browser.

I think the best solution to this may be to swallow the error so people don't encounter this issue. I'm not entirely sure why this is happening, but I would like everything to *just work* without developer configuration.

**Comment by mattmcmanus** [comment]
I hear you. 

PS. 0.5.11 fixed it. Hooray! Thanks again for the super fast response.
