### ISSUE TITLE
Getting "Refused to load the font" Error

### ISSUE THREAD

**Issue by djsegal** [tim-evans/ember-autoresize#33]
I think the error might be from quotation marks in multi-word fonts, like `Open Sans` and `Helvetica Neue`

For reference, this is what `dom_ruler.getStyles(get(this, 'element')).fontFamily.split(',')` responds with before it errors out:
* `["'Open Sans'", " 'Helvetica Neue'", " Helvetica", " Arial", " sans-serif"]`

--------

```
autoresize.js:174 [Report Only] Refused to load the font 
'data:font/opentype;base64,
T1RUTwAKAIAAAwAgQ0ZGIDTeCDQAACFkAAAZPERTSUcAAAABA…AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAA==' 
because it violates the following Content Security Policy directive: "font-src 'self' fonts.gstatic.com".
```

**Comment by djsegal** [comment]
code around the error from [autoresize.js](https://github.com/tim-evans/ember-autoresize/blob/b04c2a5a0d12e9dbecebf04239b041487b70816f/addon/mixins/autoresize.js) is

```
    fontFamilyLoaded: on('didInsertElement', function () {
      var _this = this;

      var styles = dom_ruler.getStyles(get(this, 'element'));
      var fontFamilies = styles.fontFamily.split(',');
      Ember['default'].A(fontFamilies).forEach(function (fontFamily) {
        fontLoaded['default'](trim(fontFamily)).then(function () {
          _this.scheduleMeasurement();
        }, function () {});
      });
    }),
```

**Comment by tim-evans** [comment]
Oh dear. Yeah, this is for font load detection. What browser are you working on?

**Comment by tim-evans** [comment]
This font is also the AdobeBlank that is loaded internally by the app

**Comment by djsegal** [comment]
Chrome v50

**Comment by tim-evans** [comment]
Hmm. Is this causing any errors in your app, or is this just a CSP error? I think that you need to add `data:` to your CSP file to allow this.

**Comment by djsegal** [comment]
Ok. It's just a CSP warning. Is it safe to allow all `data:`?

**Comment by tim-evans** [comment]
It should be! Ember CLI has also removed ember-cli-content-security-policy from the base default. I would reevaluated whether you need it in your app.

Cheers!

**Comment by mariobrosch** [comment]
I just overwrite fontFamilyLoaded with '' as a value. I don't want the font to be loaded at all.
