### ISSUE TITLE
Manually update size

### ISSUE THREAD

**Issue by jeremytm** [tim-evans/ember-autoresize#34]
My app contains tabs. If an autoresize textarea exists in a tab not immediately visible, it doesn't initialize to the correct size. I have to type something for it to update.

Is there an easy way tell the textarea to run a manual update?

**Comment by tim-evans** [comment]
Yeah! You can some code to the `didInsertElement` hook that looks like:

```javascript
didInsertElement() {
  this.scheduleMeasurement();
}
```

**Comment by jeremytm** [comment]
Thanks.
