### ISSUE TITLE
Add-on seems to fail when running tests on ember-cli-2.8.0

### ISSUE THREAD

**Issue by begedin** [tim-evans/ember-autoresize#40]
We are trying to use the addon within our app, and it seems to be working, but our tests fail with

```
Promise rejected after user can switch between editing and preview mode: Cannot get styles on an element that doesn't exist
```

Initially, we thought the problem is with our own lifecycle, since the editor is placed in a tab that renders or doesn't render depending on a property, but putting it outside of that scope, so it's always rendered doesn't make a difference.

**Comment by tim-evans** [comment]
I think I've encountered this in our apps as well. It seems that the lifecycle subtly changed.

**Comment by JoshSmith** [comment]
Unfortunately, I've had to remove `ember-autoresize` until we figure out what's happening here.

**Comment by JoshSmith** [comment]
@tim-evans any updates on this? Just saw a new version pushed, so wanted to check.

**Comment by tim-evans** [comment]
I'll take a look

**Comment by tim-evans** [comment]
I just released another version. Could you test against that?

**Comment by crhayes** [comment]
I was experiencing the same issue, and upgrading to the latest seems to have fixed it. Thanks bawd!

For anyone upgrading: I removed the dependency altogether (and the associated bower dep: `dom-ruler`) then reinstalled from scratch (`ember install ember-auto-resize`).

**Comment by tim-evans** [comment]
❤️
