### ISSUE TITLE
AdobeBlank injection appears to slow page load

### ISSUE THREAD

**Issue by mayatron** [tim-evans/ember-autoresize#41]
The injection of the `AdobeBlank` font appears to slow my initial page load time down by about 0.5 seconds on average. My understanding from looking at the code and and previous issues is that this font is only used to support the custom-font attribute, which my application doesn't require.

Could there an option be provided in `ember-cli-build` to disable custom font support and then not inject the AdobeBlank font?

**Comment by tim-evans** [comment]
Sure! I'd be welcome to accept a PR for that

**Comment by tim-evans** [comment]
@mayatron This is closed by #88 thanks to @jheth ❤️
