### ISSUE TITLE
Ember 2.10: ember serve fails for 0.5.19

### ISSUE THREAD

**Issue by manuel-reil** [tim-evans/ember-autoresize#44]
After upgrading to Ember 2.10 and upgrading ember-autoresize from working 0.5.16  →  0.5.19, `ember s`  fails with the error:

```
The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, stat '/mypath/tmp/source_map_concat-input_base_path-pRZd4RXb.tmp/bower_components/dom-ruler/dist/amd/dom-ruler.js'
    at Error (native)
    at Object.fs.statSync (fs.js:987:18)
    at FSMonitor._measure (/mypath/node_modules/heimdalljs-fs-monitor/index.js:66:21)
    at Object.statSync (/mypath/node_modules/heimdalljs-fs-monitor/index.js:82:30)
    at Concat.keyForFile (/mypath/node_modules/broccoli-caching-writer/index.js:87:20)
    at Array.map (native)
    at Concat.CachingWriter._conditionalBuild (/mypath/node_modules/broccoli-caching-writer/index.js:109:65)
    at /mypath/node_modules/broccoli-plugin/read_compat.js:93:34
    at tryCatch (/mypath/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/mypath/node_modules/rsvp/dist/rsvp.js:553:13)

The broccoli plugin was instantiated at:
    at Concat.Plugin (/mypath/node_modules/broccoli-plugin/index.js:7:31)
    at Concat.CachingWriter [as constructor] (/mypath/node_modules/broccoli-caching-writer/index.js:18:10)
    at new Concat (/mypath/node_modules/broccoli-concat/concat.js:33:17)
    at module.exports (/mypath/node_modules/broccoli-concat/index.js:26:10)
    at EmberApp.concatFiles (/mypath/node_modules/ember-cli/lib/broccoli/ember-app.js:369:10)
    at EmberApp._concatFiles (/mypath/node_modules/ember-cli/lib/broccoli/ember-app.js:382:15)
    at EmberApp.javascript (/mypath/node_modules/ember-cli/lib/broccoli/ember-app.js:1270:12)
    at EmberApp.toArray (/mypath/node_modules/ember-cli/lib/broccoli/ember-app.js:1646:10)
    at EmberApp.toTree (/mypath/node_modules/ember-cli/lib/broccoli/ember-app.js:1668:30)
    at module.exports (/mypath/ember-cli-build.js:67:16)
```

**Comment by tim-evans** [comment]
😿 I'll look into it

**Comment by JoshSmith** [comment]
We're seeing the same issue here:

```
The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, stat '/home/ubuntu/code-corps-ember/tmp/source_map_concat-input_base_path-SAJyFR8U.tmp/bower_components/dom-ruler/dist/amd/dom-ruler.js'
```

**Comment by JoshSmith** [comment]
So this issue happens for older versions of `dom-ruler`. Upping from `0.1.13` to `0.2.4` fixed this.

Is there a better way to track bower changes that happen here in our own projects? Or – even more ideally – remove the dependency altogether?

**Comment by tim-evans** [comment]
I'd like to make it an npm package, but I have no idea how to import native js modules into ember w/o using ember-browserify (which I don't want to use)

**Comment by JoshSmith** [comment]
Could you do something like this project does? https://github.com/jasonmit/ember-cli-moment-shim

**Comment by tim-evans** [comment]
Sure, but I'd prefer to post it directly to npm

**Comment by JoshSmith** [comment]
Well, in this case `moment` is the `npm` package. I'm not sure there's any way to outright consume a package from `npm` without some sort of a transformation step along the way to turn it into an ES6 module that can then be imported (shim, browserify, etc).

**Comment by tim-evans** [comment]
Ah, I think I didn't add the context that `dom-ruler` is already an ES6 module technically

**Comment by JoshSmith** [comment]
@tim-evans if you do release `dom-ruler` as an ES6 module, then in the very worst case I can just release an `ember-autoresize-shim` or something that uses browserify if you don't want to do so.

**Comment by JoshSmith** [comment]
Someone pointed me to https://github.com/kellyselden/ember-cli-node-modules-to-vendor. Didn't look deeply at it, but just wanted to link.

**Comment by JoshSmith** [comment]
Also seeing that you can maybe just `import` from `this.nodeModulesPath` where `this` is the current addon.

**Comment by tim-evans** [comment]
oooh, thanks!

**Comment by tim-evans** [comment]
I'll probably use that addon 👍

**Comment by JoshSmith** [comment]
Awesome glad I could help!

**Comment by denzo** [comment]
Is there any update on this? @tim-evans @JoshSmith

We are seeing a very similar issue in `0.6.1`. We have it as a `dependency` inside `in-repo-engine`.

```
Error: ENOENT: no such file or directory, open 'my-path-to-ember-project/tmp/source_map_concat-input_base_path-Ij0xwn2B.tmp/vendor/dom-ruler/dom-ruler.js'
```

We are on `"ember-cli": "~2.16.2"` and `"ember-source": "~2.16.0"`

**Comment by joshsmith** [comment]
Did you see this comment @denzo https://github.com/tim-evans/ember-autoresize/issues/44#issuecomment-275030547 ?

**Comment by denzo** [comment]
I have but a little confused sorry 🙈 on where to up the version of the `dom-ruler` as it's a dependency of this addon.

**Comment by joshsmith** [comment]
Your own `bower.json`:

```
"dependencies": {
  "dom-ruler": "0.2.4"
}
```

...should override and fix the issue seen here.

**Comment by denzo** [comment]
@JoshSmith I noticed that the current version of `ember-autoresize 0.6.1` has ` "dom-ruler": "^0.2.5"` in its dependencies. I did, however, try to use your above suggestion and set it to "0.2.4" in `bower.json`. That did not make any difference and we still get the same error.

Also, since we get the error during the build, we are a little confused how `bower` would help to address that.

@tim-evans any suggestions from your side?

**Comment by tim-evans** [comment]
Huh. `dom-ruler` shouldn't be in `bower.json` anymore. I have removed that from the dependency list.

**Comment by tim-evans** [comment]
Oh, I'm using `ember-cli-node-assets` to import this module, I guess that it's causing issues right now? Let me see what versions have been released.

Sorry about the delay, I've been on vacation

**Comment by tim-evans** [comment]
`ember-autoresize@1.0.0` should hopefully resolve these issues. The major version bump is because this version will not work with versions of ember-cli older than 2.15. Please comment / open a new issue if you're still encountering issues

**Comment by denzo** [comment]
Thanks for that @tim-evans It has fixed the issue.

However, just wanted to highlight that if this addon is a dependency of the engine the build breaks due to this I believe https://github.com/tim-evans/ember-autoresize/blob/latest/index.js#L14

As the app is the host app and there's no `ember-autoresize` module there.

We ended up having `ember-autoresize` as a host app devDependency and as the magic happens on the global Ember.TextField here https://github.com/tim-evans/ember-autoresize/blob/latest/addon/ext/text-field.js#L10 it works in the engines too.

This isn't ideal and currently we are unaware on how to address that.

**Comment by tim-evans** [comment]
We may need to ping someone from ember-cli here to help with that.
